title: Ideas de productos
description: Página documental de las ideas contempladas para el Trabajo Profesional
theme: just-the-docs
math: mathjax

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/ideas-productos"
